In [1]:
#import dependencies
import pandas as pd
import os
from sqlalchemy import create_engine
from config import postgres_pwd

In [2]:
#pull all CSV files for restaurants

#Panera
panera_df = pd.read_csv("Panera/Panera_Nutrition_Facts.csv")
#Jimmy Johns
jj_df = pd.read_csv("JimmyJohns/Jimmy_Johns_Nutrition.csv")
#Quiznos
quiznos_df = pd.read_csv("Quiznos/Quiznos CSVs/quiznos_final.csv")
#subway
subway_df = pd.read_csv("Subway/subway_file.csv")

In [3]:
#Matching all tables
panera_df.columns

Index(['restaurant_name', 'sandwich_name', 'bread_type', 'sandwich_length',
       'sandwich_description', 'calories', 'calories_from_fat', 'total_fat',
       'saturated_fat', 'trans_fat', 'protein', 'cholesterol', 'sodium',
       'total_carbohydrates', 'dietary_fiber', 'sugars'],
      dtype='object')

In [4]:
jj_df.columns

Index(['sandwich_name', 'sandwich_description', 'restaurant_name',
       'bread_type', 'sandwich_length', 'calories', 'calories_from_fat',
       'total_fat', 'saturated_fat', 'trans_fat', 'cholesterol', 'sodium',
       'total_carbohydrates', 'dietary_fiber', 'sugars', 'protein'],
      dtype='object')

In [5]:
quiznos_df.columns

Index(['Unnamed: 0', 'restaurant_name', 'sandwich_name',
       'sandwich_description', 'sandwich_length', 'bread_type', 'calories',
       'calories_from_fat', 'total_fat', 'saturated_fat', 'trans_fat',
       'cholesterol', 'sodium', 'total_carbohydrates', 'dietary_fiber',
       'sugars', 'protein'],
      dtype='object')

In [6]:
quiznos_df = quiznos_df.drop(columns = ['Unnamed: 0'])
quiznos_df

,restaurant_name,sandwich_name,sandwich_description,sandwich_length,bread_type,calories,calories_from_fat,total_fat,saturated_fat,trans_fat,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein
0,Quiznos,Classic Italian,"with capicola, salami, ham, pepperoni, provol...","4"" Sub",Bread is a white baguette unless otherwise not...,450,210,23,8.0,0.0,55,1350,40,3,5,21
1,Quiznos,Classic Italian,"with capicola, salami, ham, pepperoni, provol...","8"" Sub",Bread is a white baguette unless otherwise not...,890,430,48,15.0,1.0,90,2540,79,5,10,38
2,Quiznos,Classic Italian,"with capicola, salami, ham, pepperoni, provol...","12"" Sub",Bread is a white baguette unless otherwise not...,1260,560,63,22.0,1.0,160,3760,115,8,13,61
3,Quiznos,Classic Italian,"with capicola, salami, ham, pepperoni, provol...",Sammie,Bread is a white baguette unless otherwise not...,330,240,26,9.0,0.0,65,1240,37,1,3,18
4,Quiznos,Turkey Ranch & Swiss,"with lettuce, tomatoes, onions","4"" Sub",Bread is a white baguette unless otherwise not...,340,110,12,4.5,0.0,40,980,37,2,4,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Quiznos,Italian Meatball,"with meatballs and marinara, double portion o...",Sammie,Bread is a white baguette unless otherwise not...,460,210,23,8.0,0.0,50,970,38,6,5,25
80,Quiznos,Lobster & Seafood Salad,"with lobster & seafood salad, shredded lettuce","4"" Sub",Bread is a white baguette unless otherwise not...,300,100,11,5.0,0.0,35,850,40,2,3,12
81,Quiznos,Lobster & Seafood Salad,"with lobster & seafood salad, shredded lettuce","8"" Sub",Bread is a white baguette unless otherwise not...,610,200,22,10.0,0.5,70,1690,80,5,6,24
82,Quiznos,Lobster & Seafood Salad,"with lobster & seafood salad, shredded lettuce","12"" Sub",Bread is a white baguette unless otherwise not...,910,300,33,15.0,1.0,100,2540,120,7,10,35
83,Quiznos,Lobster & Seafood Salad,"with lobster & seafood salad, shredded lettuce",Sammie,Bread is a white baguette unless otherwise not...,300,120,13,5.0,0.0,35,810,34,4,3,11

In [7]:
subway_df.columns

Index(['Unnamed: 0', 'sandwich_name', 'calories', 'total_fat', 'trans_fat',
       'cholestrol', 'total_carbohydrates', 'dietary_fiber', 'protein',
       'sodium', 'sandwich_id', 'sugars', 'restaurant_name', 'bread_type',
       'sandwich_length', 'sandwich_type', 'saturated_fat',
       'sandwich_description'],
      dtype='object')

In [8]:
subway_df.head()

,Unnamed: 0,sandwich_name,calories,total_fat,trans_fat,cholestrol,total_carbohydrates,dietary_fiber,protein,sodium,sandwich_id,sugars,restaurant_name,bread_type,sandwich_length,sandwich_type,saturated_fat,sandwich_description
0,0,"Subway 6"" Chipotle Chicken and Cheese",450,18.0,0.0,70,46,5,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"Subway 6"" B.L.T.",340,13.0,0.0,35,37,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"Subway 6"" BBQ Rib Sandwich",580,31.0,0.0,60,54,3,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"Subway 6"" Bi Hot Pastrai",580,31.0,0.0,85,47,5,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"Subway 6"" Black Forest Ha",260,4.0,0.0,25,41,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
subway_df = subway_df.drop(columns = ['Unnamed: 0', 'sandwich_id'])
subway_df['restaurant_name'] = 'Subway'
subway_df = subway_df.drop(columns = ['sandwich_type'])
subway_df['calories_from_fat'] = ''
subway_df = subway_df.rename(columns = {'cholestrol': 'cholesterol'})
subway_df_reordered = subway_df[['sandwich_name', 'sandwich_description', 'restaurant_name',
       'bread_type', 'sandwich_length', 'calories', 'calories_from_fat',
       'total_fat', 'saturated_fat', 'trans_fat', 'cholesterol', 'sodium',
       'total_carbohydrates', 'dietary_fiber', 'sugars', 'protein']]
subway_df_reordered

,sandwich_name,sandwich_description,restaurant_name,bread_type,sandwich_length,calories,calories_from_fat,total_fat,saturated_fat,trans_fat,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein
0,"Subway 6"" Chipotle Chicken and Cheese",NaN,Subway,NaN,NaN,450,,18.0,NaN,0.0,70,NaN,46,5,NaN,7
1,"Subway 6"" B.L.T.",NaN,Subway,NaN,NaN,340,,13.0,NaN,0.0,35,NaN,37,2,NaN,5
2,"Subway 6"" BBQ Rib Sandwich",NaN,Subway,NaN,NaN,580,,31.0,NaN,0.0,60,NaN,54,3,NaN,18
3,"Subway 6"" Bi Hot Pastrai",NaN,Subway,NaN,NaN,580,,31.0,NaN,0.0,85,NaN,47,5,NaN,7
4,"Subway 6"" Black Forest Ha",NaN,Subway,NaN,NaN,260,,4.0,NaN,0.0,25,NaN,41,5,NaN,6
5,"Subway 6"" Buffalo Chicken Sandwich",NaN,Subway,NaN,NaN,340,,12.0,NaN,0.0,50,NaN,39,3,NaN,5
6,"Subway 6"" Chicken & Bacon Ranch Melt",NaN,Subway,NaN,NaN,570,,28.0,NaN,1.0,95,NaN,47,5,NaN,8
7,Subway Chicken Cordon Bleu Melt,NaN,Subway,NaN,NaN,410,,9.0,NaN,0.0,75,NaN,53,5,NaN,13
8,"Subway 6"" Chicken Mano Curry Sandwich",NaN,Subway,NaN,NaN,330,,7.0,NaN,0.0,50,NaN,43,3,NaN,8
9,"Subway 6"" Chicken Pizziola Melt",NaN,Subway,NaN,NaN,460,,16.0,NaN,0.0,80,NaN,49,6,NaN,9
10,"Subway 6"" Chicken Tikka Sandwich",NaN,Subway,NaN,NaN,290,,5.0,NaN,0.0,50,NaN,39,2,NaN,5
11,"Subway 6"" Chicken Vindaloo Sandwich",NaN,Subway,NaN,NaN,340,,9.0,NaN,0.0,50,NaN,42,3,NaN,6
12,"Subway 6"" Cold Cut Cobo",NaN,Subway,NaN,NaN,370,,13.0,NaN,0.0,50,NaN,46,5,NaN,7
13,"Subway 6"" Genoa Salai Sandwich",NaN,Subway,NaN,NaN,430,,23.0,NaN,0.0,60,NaN,40,2,NaN,5
14,Subway Ha & Jack Slider,NaN,Subway,NaN,NaN,150,,4.5,NaN,0.0,20,NaN,17,1,NaN,1
15,"Subway 6"" Italian B.M.T.",NaN,Subway,NaN,NaN,410,,16.0,NaN,0.0,45,NaN,46,5,NaN,8
16,Subway Italian Spice Slider,NaN,Subway,NaN,NaN,230,,14.0,NaN,0.0,30,NaN,18,1,NaN,1
17,Subway Little Cheesesteak Slider,NaN,Subway,NaN,NaN,180,,7.0,NaN,0.0,15,NaN,19,1,NaN,2
18,Subway Little Turkey Slider,NaN,Subway,NaN,NaN,200,,10.0,NaN,0.0,25,NaN,17,1,NaN,1
19,"Subway 6"" Meatball Marinara",NaN,Subway,NaN,NaN,480,,18.0,NaN,1.0,30,NaN,59,8,NaN,12
20,"Subway 6"" Oven Roasted Chicken",NaN,Subway,NaN,NaN,320,,5.0,NaN,0.0,25,NaN,47,5,NaN,8
21,"Subway 6"" Paneer Tikka Sandwich",NaN,Subway,NaN,NaN,570,,30.0,NaN,0.5,70,NaN,48,3,NaN,7
22,"Subway 6"" Roast Beef",NaN,Subway,NaN,NaN,320,,5.0,NaN,0.0,40,NaN,45,5,NaN,7
23,"Subway 6"" Rotisserie Style Chicken",NaN,Subway,NaN,NaN,350,,6.0,NaN,0.0,50,NaN,44,5,NaN,7
24,"Subway 6"" Southwest Chicken Club Sandwich",NaN,Subway,NaN,NaN,580,,29.0,NaN,0.0,95,NaN,43,4,NaN,6
25,"Subway 6"" Spicy Italian",NaN,Subway,NaN,NaN,480,,24.0,NaN,1.0,50,NaN,46,5,NaN,8
26,"Subway 6"" Steak and Cheese",NaN,Subway,NaN,NaN,380,,10.0,NaN,0.0,50,NaN,48,5,NaN,8
27,"Subway 6"" Subway Club",NaN,Subway,NaN,NaN,310,,5.0,NaN,0.0,40,NaN,46,5,NaN,7
28,"Subway 6"" Subway Melt (includes cheese)",NaN,Subway,NaN,NaN,370,,11.0,NaN,0.0,45,NaN,47,5,NaN,8
29,"Subway 6"" Subway Seafood Sensation",NaN,Subway,NaN,NaN,420,,19.0,NaN,0.0,20,NaN,51,5,NaN,8
30,"Subway 6"" Sweet Onion Chicken Teriyaki",NaN,Subway,NaN,NaN,380,,5.0,NaN,0.0,50,NaN,59,5,NaN,18
31,"Subway 6"" Tuna",NaN,Subway,NaN,NaN,470,,24.0,NaN,0.0,30,NaN,44,5,NaN,6
32,"Subway 6"" Turkey & Bacon Avocado",NaN,Subway,NaN,NaN,390,,13.0,NaN,0.0,30,NaN,49,8,NaN,7
33,"Subway 6"" Turkey Breast",NaN,Subway,NaN,NaN,280,,4.0,NaN,0.0,20,NaN,46,5,NaN,7
34,"Subway 6"" Turkey Breast & Ha",NaN,Subway,NaN,NaN,280,,4.0,NaN,0.0,20,NaN,46,5,NaN,8
35,"Subway 6"" Turkey Italiano Melt (with Provolone)",NaN,Subway,NaN,NaN,490,,24.0,NaN,1.0,50,NaN,47,5,NaN,8
36,"Subway 6"" Veie Delite",NaN,Subway,NaN,NaN,230,,3.0,NaN,0.0,0,NaN,44,5,NaN,6
37,"Subway 6"" Veie Patty",NaN,Subway,NaN,NaN,390,,7.0,NaN,0.0,10,NaN,56,8,NaN,8

In [10]:
#combine all csv files
starter_df = jj_df.append(quiznos_df)
starter_2_df = starter_df.append(panera_df)
all_sandwiches_df = starter_2_df.append(subway_df)
all_sandwiches_df

,sandwich_name,sandwich_description,restaurant_name,bread_type,sandwich_length,calories,calories_from_fat,total_fat,saturated_fat,trans_fat,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein
0,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,Unwich,na,190,100,11,6.0,0.0,50,900,4,0,2.0,20
1,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,French Bread,8 Inch,120,120,14,6.0,0.0,50,"1,690",5,5,1.0,34
2,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,Thick-Sliced Wheat,na,560,180,19,6.0,0.0,50,"1,290",4,4,9.0,36
3,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,French Bread,16 Inch,"1,160",250,250,12.0,0.0,105,"3,370",154,10,2.0,69
4,SLIM 2,Made with hand-sliced roast beef and served on...,Jimmy Johns,Unwich,na,90,25,3,2.0,0.0,45,490,1,0,1.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,"Subway 6"" Turkey Breast",NaN,Subway,NaN,NaN,280,,4,NaN,0.0,20,NaN,46,5,NaN,7
34,"Subway 6"" Turkey Breast & Ha",NaN,Subway,NaN,NaN,280,,4,NaN,0.0,20,NaN,46,5,NaN,8
35,"Subway 6"" Turkey Italiano Melt (with Provolone)",NaN,Subway,NaN,NaN,490,,24,NaN,1.0,50,NaN,47,5,NaN,8
36,"Subway 6"" Veie Delite",NaN,Subway,NaN,NaN,230,,3,NaN,0.0,0,NaN,44,5,NaN,6
37,"Subway 6"" Veie Patty",NaN,Subway,NaN,NaN,390,,7,NaN,0.0,10,NaN,56,8,NaN,8

In [11]:
all_sandwiches_df = all_sandwiches_df.reset_index(drop = True)
all_sandwiches_df

,sandwich_name,sandwich_description,restaurant_name,bread_type,sandwich_length,calories,calories_from_fat,total_fat,saturated_fat,trans_fat,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein
0,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,Unwich,na,190,100,11,6.0,0.0,50,900,4,0,2.0,20
1,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,French Bread,8 Inch,120,120,14,6.0,0.0,50,"1,690",5,5,1.0,34
2,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,Thick-Sliced Wheat,na,560,180,19,6.0,0.0,50,"1,290",4,4,9.0,36
3,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,French Bread,16 Inch,"1,160",250,250,12.0,0.0,105,"3,370",154,10,2.0,69
4,SLIM 2,Made with hand-sliced roast beef and served on...,Jimmy Johns,Unwich,na,90,25,3,2.0,0.0,45,490,1,0,1.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,"Subway 6"" Turkey Breast",NaN,Subway,NaN,NaN,280,,4,NaN,0.0,20,NaN,46,5,NaN,7
248,"Subway 6"" Turkey Breast & Ha",NaN,Subway,NaN,NaN,280,,4,NaN,0.0,20,NaN,46,5,NaN,8
249,"Subway 6"" Turkey Italiano Melt (with Provolone)",NaN,Subway,NaN,NaN,490,,24,NaN,1.0,50,NaN,47,5,NaN,8
250,"Subway 6"" Veie Delite",NaN,Subway,NaN,NaN,230,,3,NaN,0.0,0,NaN,44,5,NaN,6
251,"Subway 6"" Veie Patty",NaN,Subway,NaN,NaN,390,,7,NaN,0.0,10,NaN,56,8,NaN,8

In [12]:
all_sandwiches_df.columns

Index(['sandwich_name', 'sandwich_description', 'restaurant_name',
       'bread_type', 'sandwich_length', 'calories', 'calories_from_fat',
       'total_fat', 'saturated_fat', 'trans_fat', 'cholesterol', 'sodium',
       'total_carbohydrates', 'dietary_fiber', 'sugars', 'protein'],
      dtype='object')

In [17]:
all_sandwiches_df = all_sandwiches_df.rename(columns = {'calories': 'calories_cal',
                                    'calories_from_fat': 'calories_from_fat_cal',
                                    'total_fat': 'total_fat_grams',
                                    'saturated_fat': 'saturated_fat_grams' ,
                                    'trans_fat': 'trans_fat_grams',
                                    'cholesterol': 'cholesterol_mg',
                                    'sodium': 'sodium_mg',
                                    'total_carbohydrates': 'total_carbohydrates_grams',
                                    'dietary_fiber': 'dietary_fiber_grams',
                                    'sugars': 'sugars_grams',
                                    'protein': 'protein_grams'})
all_sandwiches_df = all_sandwiches_df.fillna("na")
all_sandwiches_df = all_sandwiches_df.replace("","na")
all_sandwiches_df

,sandwich_name,sandwich_description,restaurant_name,bread_type,sandwich_length,calories_cal,calories_from_fat_cal,total_fat_grams,saturated_fat_grams,trans_fat_grams,cholesterol_mg,sodium_mg,total_carbohydrates_grams,dietary_fiber_grams,sugars_grams,protein_grams
0,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,Unwich,na,190,100,11,6,0.0,50,900,4,0,2,20
1,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,French Bread,8 Inch,120,120,14,6,0.0,50,"1,690",5,5,1,34
2,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,Thick-Sliced Wheat,na,560,180,19,6,0.0,50,"1,290",4,4,9,36
3,SLIM 1,Made with hand-sliced smoked ham and provolone...,Jimmy Johns,French Bread,16 Inch,"1,160",250,250,12,0.0,105,"3,370",154,10,2,69
4,SLIM 2,Made with hand-sliced roast beef and served on...,Jimmy Johns,Unwich,na,90,25,3,2,0.0,45,490,1,0,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,"Subway 6"" Turkey Breast",na,Subway,na,na,280,na,4,na,0.0,20,na,46,5,na,7
248,"Subway 6"" Turkey Breast & Ha",na,Subway,na,na,280,na,4,na,0.0,20,na,46,5,na,8
249,"Subway 6"" Turkey Italiano Melt (with Provolone)",na,Subway,na,na,490,na,24,na,1.0,50,na,47,5,na,8
250,"Subway 6"" Veie Delite",na,Subway,na,na,230,na,3,na,0.0,0,na,44,5,na,6
251,"Subway 6"" Veie Patty",na,Subway,na,na,390,na,7,na,0.0,10,na,56,8,na,8

In [14]:
#exporting final file to CSV
all_sandwiches_df.to_csv("final_sandwich_data.csv")

In [15]:
#establish connection
rds_connection_string = f"postgres:{postgres_pwd}@localhost:5432/for-now"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [16]:
all_sandwiches_df.to_sql(name='sandwiches', con=engine, if_exists='append', index=False)

KeyError: 'calories(cal'

In [27]:
exercise_df = pd.read_csv("Exercise_Scrape/per_min_exercise.csv")
exercise_df['exercise_id'] = exercise_df.index
exercise_df

,exercise_id,exercise,130 lbs,155 lbs,180 lbs,205 lbs
0,0,"Cycling,mountain bike, bmx",8.4,10.0,11.6,13.2
1,1,"Cycling,<10 mph, leisure bicycling",3.9,4.7,5.4,6.2
2,2,"Cycling,>20 mph, racing",15.7,18.8,21.8,24.8
3,3,"Cycling,10-11.9 mph, light",5.9,7.0,8.2,9.3
4,4,"Cycling,12-13.9 mph, moderate",7.9,9.4,10.9,12.4
...,...,...,...,...,...,...
218,218,"Cleaning,dusting",2.5,2.9,3.4,3.9
219,219,Takingout trash,3.0,3.5,4.1,4.6
220,220,"Walking,pushing a wheelchair",3.9,4.7,5.4,6.2
221,221,"Teachphysical education,exercise class",3.9,4.7,5.4,6.2
222,222,Teachexercise classes (& participate),6.4,7.6,8.8,10.1

In [23]:
exercise_df.to_sql(name='exercises', con=engine, if_exists='append', index=False)