In [2]:
#import dependencies

import pandas as pd
import os

In [5]:
#import CSVs from 'Quiznos CSV' folder

quiznos_1 = pd.read_csv("Quiznos CSVs/Quiznos_1.csv")
quiznos_2 = pd.read_csv("Quiznos CSVs/Quiznos_2.csv")
quiznos_3 = pd.read_csv("Quiznos CSVs/Quiznos_3.csv")

quiznos_3

,"Black Angus Steakhouse - with provolone, cheddar, sautéed mushrooms & onions, grille sauce on rosemary parmesan bread",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,"4"" Sub",390.0,120.0,13.0,6.0,0.0,50.0,1010.0,44.0,2.0,9.0,23.0
1,"8"" Sub",780.0,240.0,27.0,13.0,0.0,100.0,2010.0,88.0,4.0,19.0,47.0
2,"12"" Sub",1170.0,360.0,40.0,19.0,0.5,150.0,3060.0,134.0,6.0,30.0,70.0
3,Sammie,390.0,140.0,15.0,6.0,0.0,50.0,1000.0,39.0,4.0,10.0,23.0
4,Half Salad,310.0,110.0,12.0,6.0,0.0,50.0,980.0,31.0,3.0,24.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...
78,Half Salad,300.0,220.0,24.0,4.0,0.0,40.0,980.0,12.0,3.0,4.0,8.0
79,Bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,"Artisan White 4""",170.0,15.0,1.5,0.5,0.0,0.0,340.0,33.0,1.0,2.0,6.0
81,"Artisan Wheat 4""",150.0,15.0,1.5,0.0,0.0,0.0,260.0,29.0,3.0,3.0,6.0
82,"Rosemary Parmesan 4""",140.0,20.0,2.5,1.0,0.0,5.0,270.0,25.0,1.0,2.0,5.0